# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_member_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='friend',
        ),
        migrations.AlterField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(related_name='_member_following_+', to='social.Member'),
        ),
    ]
