# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20160211_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='friends',
            field=models.ManyToManyField(related_name='_member_friends_+', to='social.Member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(to='social.Member'),
        ),
    ]
