# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20160211_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(related_name='_member_following_+', to='social.Member'),
        ),
    ]
