# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_remove_member_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(to='social.Member'),
        ),
    ]
