# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 12:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_auto_20160215_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(related_name='_member_following_+', to='social.Member'),
        ),
    ]
