# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20160216_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='following',
            field=models.ManyToManyField(to='social.Member'),
        ),
    ]
