# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_requests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='following',
        ),
        migrations.AddField(
            model_name='requests',
            name='requestFrom',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='requests',
            name='requestTo',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
