# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 13:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20160216_1313'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Request',
        ),
    ]
