# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='city',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='date',
            field=models.DateTimeField(null=True, verbose_name=b'date created'),
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(max_length=16, null=True),
        ),
    ]
